### ISSUE TITLE
Setting entry title

### ISSUE THREAD

**Issue by andersdra** [hrehfeld/python-keepassxc-browser#11]
Is it possible to set entry title?
Seems like it is the 'id' field of set-login

{
    "action": "set-login",
    "url": "<snip>",
    "submitUrl": "<snip>",
    "id": "testclient",
    "nonce": "tZvLrBzkQ9GxXq9PvKJj4iAnfPT0VZ3Q",
    "login": "user1",
    "password": "passwd1",
    "group": "<group name>",
    "groupUuid": "<group UUID>",
    "uuid": "<entry UUID>"
}

**Comment by hrehfeld** [comment]
I don't understand. Can you elaborate what you actually wanna do? I.e. expected/actual behavior, etc.
