### ISSUE TITLE
Make socket path configurable

### ISSUE THREAD

**Issue by piegamesde** [hrehfeld/python-keepassxc-browser#19]
Apparently, Keepass has changed the default socket path to `org.keepassxc.KeePassXC.BrowserServer` since the latest release. This wouldn't be a problem if the socket path was configurable, which it isn't.

**Comment by omgold** [comment]
As of keepassxc 2.6.0 the socket at $XDG_RUNTIME_DIR/kpxc_server no longer exists, so the library won't work anymore without  changing the default in protocol.py to the path mentioned above.

**Comment by hrehfeld** [comment]
Can you help me and try simply changing the hardcoded value, then creating a pull request? I guess the path isn't likely to change again in the near future, so I think hardcoding it is fine?
