### ISSUE TITLE
[BUG] Not possible to update an existing entry

### ISSUE THREAD

**Issue by MarkusFreitag** [hrehfeld/python-keepassxc-browser#28]
When you pass the optional parameter `entry_id` to `Connection.set_login`, in order to update an already existing database entry, it will instead create a new one. It seems that this param does in fact not have any influence on the database entry, as the correct property is called `uuid`. By renaming `entry_id` into `uuid` in the mentioned function, updating an existing entry works as expected.

https://github.com/hrehfeld/python-keepassxc-browser/blob/master/keepassxc_browser/protocol.py#L254-L266

**Comment by hrehfeld** [comment]
Thanks for the report! Fixed in 81356d054e05c5fe7bcd3a48b1b7377fda71e566
