### ISSUE TITLE
Test if database is open

### ISSUE THREAD

**Issue by piegamesde** [hrehfeld/python-keepassxc-browser#5]
I use a variation of the `test.py` script to retrieve some passwords. But when the database is closed, it simply throws a generic `keepassxc_browser.protocol.ProtocolError: Database not opened` somewhere in the code.

I'd like to have the ability to cleanly check if the database is open before starting to retrieve passwords (ideally without requiring identification).

**Comment by hrehfeld** [comment]
Thanks for the report! Can you provide a minimal example?

**Comment by piegamesde** [comment]
`test.py` is already pretty minimal (note that I commented out line 18).

If I run it when the database is closed `c.test_associate(id)` in line 20 will return false. This will cause `c.associate(id)` in line 21 to throw a protocol error.

I'd like to add something like `if c.is_open():` to abort the whole process if the database is locked.

**Comment by Phidica** [comment]
You can use `get_database_hash()` to test if the database is open. ie,
```python
try:
    c.get_database_hash(id)
except ProtocolError as ex:
    print(ex) # "Database not opened"
    exit(1)
```

**Comment by piegamesde** [comment]
Hm, I commented the database hash part out because when I run this and the database is open, I get

```
>>> c.get_database_hash(id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/keepassxc_browser/protocol.py", line 198, in get_database_hash
    resp_message = self.send_encrypted_command(identity, command)
  File "/usr/lib/python3.7/site-packages/keepassxc_browser/protocol.py", line 172, in send_encrypted_command
    resp = self.send_command(identity, command, nonce, next_nonce)
  File "/usr/lib/python3.7/site-packages/keepassxc_browser/protocol.py", line 166, in send_command
    raise ProtocolError(resp['error'])
keepassxc_browser.protocol.ProtocolError: Cannot decrypt message
```

Don't know if this is related.

**Comment by Phidica** [comment]
Hm, I haven't seen that error before. Even if the access key hasn't been associated to the database we should be able to read the response to this request. What version of KeePassXC are you using?

**Comment by piegamesde** [comment]
```
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.3
Debugging mode is disabled.

Operating system: Antergos Linux
CPU architecture: x86_64
Kernel: linux 5.0.13-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4
```

**Comment by Phidica** [comment]
Ah, you're using a much newer version of KeePassXC than I am. Perhaps the interface has changed... It looks like that error message actually means KeePassXC couldn't decrypt the message we had sent, not that we couldn't read its response.

As a workaround, you can also put the `try / except` block on the `associate()` command:
```python
if not c.test_associate(id):
    try:
        associated_name = c.associate(id)
    except ProtocolError as ex:
        print(ex)
        exit(1)
```

**Comment by piegamesde** [comment]
I think
```
try:
    c.get_database_hash(id)
except ProtocolError as ex:
    print(ex) # "Database not opened"
    exit(1)
```

solves my issue, but I'd be happy to have a convenience method to do this for me.

**Comment by piegamesde** [comment]
I cannot import `ProtocolError`:

```
Traceback (most recent call last):
  File "keepassxc.py", line 2, in <module>
    from keepassxc_browser import Connection, Identity, ProtocolError
ImportError: cannot import name 'ProtocolError' from 'keepassxc_browser' (~/.local/lib/python3.7/site-packages/keepassxc_browser/__init__.py)
```

My code:

```
try:
    print(c.get_database_hash(id))
except ProtocolError as ex:
    print("Database not opened")
```

**Comment by Phidica** [comment]
Ah, right, `ProtocolError` isn't available in the same way the classes are. You need a separate import line:
```python
 from keepassxc_browser.protocol import ProtocolError
```

**Comment by piegamesde** [comment]
It works now as expected, thanks.
