### ISSUE TITLE
`get_database_hash` throws error

### ISSUE THREAD

**Issue by piegamesde** [hrehfeld/python-keepassxc-browser#6]
```
>>> c.get_database_hash(id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/keepassxc_browser/protocol.py", line 198, in get_database_hash
    resp_message = self.send_encrypted_command(identity, command)
  File "/usr/lib/python3.7/site-packages/keepassxc_browser/protocol.py", line 172, in send_encrypted_command
    resp = self.send_command(identity, command, nonce, next_nonce)
  File "/usr/lib/python3.7/site-packages/keepassxc_browser/protocol.py", line 166, in send_command
    raise ProtocolError(resp['error'])
keepassxc_browser.protocol.ProtocolError: Cannot decrypt message
```

The database is open and I have a valid identification.

_Originally posted in https://github.com/hrehfeld/python-keepassxc-browser/issues/5#issuecomment-490446678_

**Comment by omgold** [comment]
Same problem here. It seems latest version (I'm on 2.4.1) does not accept unencrypted requests for database hash. Changing the function to this seems to work:

```
def get_database_hash(self, identity):
    action = 'get-databasehash'
    message = create_message(action)
    resp_message = self.encrypt_message_send_command(identity, action, message)
    return resp_message['hash']
```

**Comment by piegamesde** [comment]
@omgold If this code works for you, would you mind creating a pull request?

**Comment by Phidica** [comment]
I think we should also be sure to maintain backwards compatibility to older versions of KeePassXC. How could this be implemented?

**Comment by varjolintu** [comment]
Btw, I don't even remember when the `get-databasehash` was not encrypted. It's a long time ago. Even my quick-and-ugly Python 2 client deals that one with encrypted response.

So I don't need you need to think about backward compatibility.

**Comment by hrehfeld** [comment]
Iirc there was no version information in the protocol, but I'd have to double check. If backwards compatability is complicated to maintain, I would prefer supporting the latest version only.

**Comment by varjolintu** [comment]
The version information in the protocol indeed sucks. I'll see that it will be better in the future.

**Comment by Phidica** [comment]
Well, the current implementation works as is for KeePassXC 2.3.4. I assumed that sending an encrypted request instead would be unexpected and unsupported for this version, but if that isn't the case and KeePassXC has actually accepted this method when encrypted for some time, then I see it's not so much an issue

**Comment by Phidica** [comment]
~~I tested the change recommended by @omgold against KeePassXC 2.3.4 (released 24 Aug, 2018). While the database was locked there was no problem, but when the database was already unlocked I got the following error:~~
```                                                              
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    c.get_database_hash(id)
  File "<snip>/protocol.py", line 197, in get_database_hash
    resp_message = self.encrypt_message_send_command(identity, action, message)
  File "<snip>/protocol.py", line 179, in encrypt_message_send_command
    return self.send_encrypted_command(identity, command, nonce)
  File "<snip>/protocol.py", line 173, in send_encrypted_command
    resp = self.send_command(identity, command, nonce, next_nonce)
  File "<snip>/protocol.py", line 168, in send_command
    check_nonces(resp, next_nonce)
  File "<snip>/protocol.py", line 75, in check_nonces
    assert response_nonce == expected_nonce
AssertionError
```
~~So yes, making this change will break backwards compatibility.~~

Edit: Never mind, trying it a second time works for some reason. That must have been a once-off failure.

**Comment by piegamesde** [comment]
It works fine for me, too. The only problem I see with this (and this is more a protocol issue) is before having associated with KeePass, there is no way to tell if the database is open or not. I can see why they made this since it has some security/privacy implications. On the other hand, it breaks the `test.py` script since there is no way to distinguish closed database and not associated anymore.

**Comment by Phidica** [comment]
I'm not sure that's true? From my testing, if the database is locked then `get_database_hash()` throws a ProtocolError with message "Database not opened". If it is unlocked then it returns the hash, even if the database hasn't been associated yet.

**Comment by varjolintu** [comment]
Locked databases should always return an empty hash. This is because there can be multiple databases, some open and some closed, and KeePassXC sends messages to all connected clients when a database is locked or unlocked.

**Comment by piegamesde** [comment]
Unrelated:

> KeePassXC sends messages to all connected clients when a database is locked or unlocked.

How to retrieve such a notification?

**Comment by varjolintu** [comment]
@piegamesde By listening the same socket.

**Comment by Nekmo** [comment]
Is KeepassXC the problem? I had a plugin to get the credentials using KeepassHTTP, but the support has been removed and this new protocol seems to be very unstable. Maybe KeepassXC should recover the support for KeepassHTTP.

**Comment by varjolintu** [comment]
@Nekmo KeePassXC is not recovering support for KeePassHTTP. This has been discussed multiple times before. Could you elaborate how you find the new protocol unstable?

**Comment by piegamesde** [comment]
I don't know what's happened, but I cannot reproduce this anymore. Maybe it was a bug in KeepassXC?

**Comment by piegamesde** [comment]
Nope, it was me being stupid. Still there. Sorry for two unnecessary notifications ^^

**Comment by Nekmo** [comment]
> @Nekmo KeePassXC is not recovering support for KeePassHTTP. This has been discussed multiple times before. Could you elaborate how you find the new protocol unstable?

I am using python-keepassxc-browser for this project: https://github.com/Nekmo/ansible-keepass . 

It usually works correctly, but randomly does not return credentials in the same order and in the correct way. Maybe it's a issue with KeepassXC. But before I used KeepassHTTP and it worked perfectly.

It is very frustrating that the KeepassXC team has removed KeepassHTTP mode. This mode had better support, is better documented and is more mature.

Now I am using the pam_ssh_agent_auth module together with Ansible. It works much better.
